# Generated by Django 6.0 on 2026-01-10 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.mecanico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('numero_os', models.CharField(max_length=20, unique=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO_PECAS', 'Aguardando Peças'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20)),
                ('mecanico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.mecanico')),
                ('orcamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.orcamento')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='LaudoTecnico',
            fields=[
                ('id_laudo', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico_detalhado', models.TextField()),
                ('acoes_corretivas', models.TextField(blank=True, null=True)),
                ('recomendacoes_futuras', models.TextField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.mecanico')),
                ('os', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laudo', to='oficina.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id_checklist', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_combustivel', models.CharField(max_length=50)),
                ('avarias_lataria', models.TextField(blank=True, null=True)),
                ('pneus_estado', models.CharField(default='Bom estado', max_length=100)),
                ('possivel_defeito', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('mecanico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.mecanico')),
                ('os', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='oficina.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('custo_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_estoque', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=5)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMovimentacao',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.servico')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='oficina.orcamento')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='oficina.ordemservico')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficina.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id_item_venda', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficina.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='oficina.venda')),
            ],
        ),
    ]
