# Generated by Django 6.0 on 2026-01-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='oficina.produto')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
