# Generated by Django 5.1.4 on 2026-01-05 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_update_checklist'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudotecnico',
            name='acoes_corretivas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laudotecnico',
            name='data_conclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='laudotecnico',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.mecanico'),
        ),
        migrations.AlterField(
            model_name='laudotecnico',
            name='recomendacoes_futuras',
            field=models.TextField(blank=True, null=True),
        ),
    ]
