# Generated by Django 6.0 on 2026-01-14 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0004_movimentacaoestoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='valor_total',
        ),
    ]
