# Generated by Django 6.0 on 2026-01-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0005_remove_orcamento_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
