# Generated by Django 6.0 on 2026-01-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0006_orcamento_descricao'),
        ('usuarios', '0002_administrador'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='veiculos.agendamento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='veiculos.agendamento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='oficina.checklist'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='avarias_lataria',
            field=models.TextField(blank=True, default='Sem avarias visíveis', help_text='Descreva avarias na lataria,vidros, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.mecanico'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='oficina.ordemservico'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='pneus_estado',
            field=models.CharField(max_length=100),
        ),
    ]
