# Generated by Django 6.0 on 2026-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0007_checklist_agendamento_orcamento_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_INICIO', 'Aguardando Início'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO_PECAS', 'Aguardando Peças'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO_INICIO', max_length=20),
        ),
    ]
