# Generated by Django 6.0 on 2026-01-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalhes_padrao', models.TextField(blank=True, null=True, verbose_name='Detalhamento Padrão')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fim', models.DateTimeField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluído')], default='AGENDADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='usuarios.cliente')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='usuarios.mecanico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.servico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='veiculos.veiculo')),
            ],
            options={
                'ordering': ['horario_inicio'],
            },
        ),
    ]
