# Generated by Django 5.1.4 on 2025-12-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_cliente_user'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fim', models.DateTimeField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluído')], default='AGENDADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='usuarios.cliente')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='usuarios.mecanico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.servico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='veiculos.veiculo')),
            ],
            options={
                'ordering': ['horario_inicio'],
            },
        ),
    ]
