# Generated by Django 5.1.4 on 2025-12-17 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecanico',
            name='is_mecanico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mecanico',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mecanico', to=settings.AUTH_USER_MODEL),
        ),
    ]
